[CI] Config file adjustments - flow adjustment

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: CI Pipeline
+name: CI / CD Pipeline
 
 on:
   push:
@@ -8,7 +8,8 @@ on:
 
 
 jobs:
-  build-test:
+  setup:
+    name: ⚙️ Environment Setup & Dependencies
     runs-on: ubuntu-latest
 
     steps:
@@ -25,11 +26,14 @@ jobs:
       run: | 
         python -m pip install --upgrade pip 
         pip install -r requirements.txt
-# skipped for now, as it requires Docker to run and we are testing outside Docker and DB conection is added in the main app
-#    - name: Run basic FastAPI checkout (Test outside Docker)
-#      working-directory: backend
-#      run: |
-#        python -c "import main; print('✅ App module loaded successfully')" 
+
+
+  docker-build:
+    name: 🐳 Docker Compose Integration Test
+    runs-on: ubuntu-latest
+    needs: setup    
+    
+    steps:
 
     - name: Build and run with Docker compose 
       run: |
@@ -47,10 +51,12 @@ jobs:
         done
         echo "App did not start in time."
 
-    - name: Test if app is live (welcome page)
+    - name: Run Smoke Tests
       run: |
         sleep 3
         curl -f http://localhost:8000/
+        curl -f http://localhost:8000/db-check
+        curl -f http://localhost:8000/history || echo "History endpoint failed, can be empty if no conversions yet"
 
     - name: Stop Docker containers
       run: docker compose -f docker-compose.yaml down
@@ -58,7 +64,8 @@ jobs:
 
 
   deploy: 
-    needs: build-test
+    name: 🚀 Deploy to EC2
+    needs: docker-build
     runs-on: ubuntu-latest
 
     steps:
